version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - angular
    networks:
      - dc-network

  angular:
    build:
      context: ./angular-app
    ports:
      - 4200:4200
    networks:
      - dc-network

  springboot:
    build:
      context: ./spring-boot-app
    ports:
      - 8080:8080
    environment:
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=password1
      - JDBC_DATABASE_URL=jdbc:postgresql://postgres:5432/springbootdb
    depends_on:
      - postgres
    networks:
      - dc-network

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=springbootdb
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - dc-network

networks:
  dc-network:


